### ISSUE TITLE
How did you generate the Metadata?

### ISSUE THREAD

**Issue by licaoyuan123** [deepmind/rc-data#12]
Thank you for sharing the data!

I'm wondering how did you generate the [Metadata](https://storage.googleapis.com/deepmind-data/20150824/data.tar.gz)? I mean the data files that contains entities, tokens and urls.

Is it possible for you to opensource the code to generate the Metadata files? Many thanks.

**Comment by lespeholt** [comment]
Hi,

We used an in-house tokenizer and entity analyzer. Unfortunately we can't open source that part but you should be able to do something similar with open source equivalents.
