### ISSUE TITLE
Official train, validation and test split for cnn stories?

### ISSUE THREAD

**Issue by mikelkl** [deepmind/rc-data#16]
Hi there, I'll trying reproduce summarization paper's work on cnn/dailymail dataset, and I noticed that many papers employ the same  train, validation and test split on cnn/dailymail stories files. My dataset was download from [DMQA](https://cs.nyu.edu/~kcho/DMQA/), it doesn't provide existed split for stories files. May I ask if there is a official way to do that?

**Comment by lespeholt** [comment]
If you download the questions too, they contain all the training/validation/test urls and you can use them to create the split for the stories.
Best, Lasse

**Comment by mikelkl** [comment]
Thank you very much!
