### ISSUE TITLE
Checksums

### ISSUE THREAD

**Issue by stephenroller** [deepmind/rc-data#3]
Thank you for sharing this data.

Maybe you can post a file containing checksums after running the script? It could be as simple as "find . -type f -exec md5sum"

**Comment by lespeholt** [comment]
I apologize for not replying, I haven't received notifications. I'll look into this. Actually, the filenames for the final questions are checksums so I can release those. That said, if you end up getting the same number of question/answer pairs in the test sets it's unlikely that they are different.

**Comment by lespeholt** [comment]
I'm going on vacation today, but I'll attend to this first thing when I'm back.

**Comment by lespeholt** [comment]
Hi,

I've now released the checksums of the test sets. Let me know of any problems.
