### ISSUE TITLE
IOError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by mbosnjak** [deepmind/rc-data#4]
Tnx for the data!

I just wanted to point out that in some cases I get the aforementioned (too many open file) error on OSX, which I seemingly fix with "ulimit -n 1200"
Just a comment if anyone else stumbles upon the same problem.

Cheers

**Comment by lespeholt** [comment]
I apologize for not replying, I haven't received Github notifications.

I think setting --request_parallelism to something lower than 200 may also fix the problem.

**Comment by lespeholt** [comment]
Closing for now.
