### ISSUE TITLE
unsolved problems when using vpn

### ISSUE THREAD

**Issue by zhzou2020** [deepmind/rc-data#9]
I'm a researcher from China.
Due to the GFW, we cannot directly access the websites that is provided in the script.
That is the reason why I need to use the vpn.
And when using a vpn and set the http_proxy(under Linux),I found the script cannot work properly.

Like this:

<code>
File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 381, in send
    raise ProxyError(e)
requests.exceptions.ProxyError: Cannot connect to proxy. Socket error: [Errno 110] Connection timed out.
</code>

I suppose it's an error that is associated with the requests package.
And I wonder if there's a place where I can directly download the dataset instead of the script that generates it.

**Comment by lespeholt** [comment]
Hi,

Unfortunately I'm not aware of anyone who stores the dataset. I'll keep the bug open and let you know of any updates.

**Comment by lespeholt** [comment]
Hi,

See the updated readme for downloading a processed version. I'm closing the issue.

Best, Lasse
